import type { Metadata } from "next";
import { Inter, Lobster } from "next/font/google";
import { AblyProvider } from "./contexts/AblyContext";
import { TranslationProvider } from "./contexts/TranslationContext";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const lobster = Lobster({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lobster",
  weight: "400",
});

export const metadata: Metadata = {
  title: "ChatTalk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={lobster.variable}>
      <body className={inter.className}>
        <AblyProvider ABLY_API_KEY={process.env.ABLY_API_KEY}>
          <TranslationProvider>
            {children}
          </TranslationProvider>
        </AblyProvider>
      </body>
    </html>
  );
}
